# Options par défaut de l'application (Manuel/app/options.adoc) 
# — un carnet peut rédéfinir par son carnet.infos
tdm_position: end
build_unknown_song: true
text_column_guter: 1cm
text_font: Garamond
format: 8.25 x 6

# songs_dir
# Chemin absolu du dossier des chansons
songs_dir: /Users/philippeperret/Documents/Musique/Carnets-de-chant/CHANSONS

# Chemin absolu du dossier des carnets
songbooks_dir: null

# Application (nom ou chemin) utilisée pour éditer les fichiers d'une chanson
user_song_editor: CotEditor
