[[console-command]]
=== Commande `songbook` ===

Commençons justement par cette commande `songbook` qui permet de gérer les carnets, les chansons, ainsi que tous les éléments qui leur sont utiles, les diagrammes d'accords, les tablatures, etc.

Un <<interactive-mode, mode interactif>> existe, avec l'option `-i`. Dans ce mode, toutes les commandes frappées sont interpréter dans __**SongBook**__.

Dans cette aide, vous saurez que l'on se trouve en mode interactif lorsqu'il y a aura cette invite :

----
🎸> <je suis en mode interactif>
----

Utiliser `songbook -h` ou `songbook --help` pour obtenir une aide rapide (moins détaillée qu'ici) — ou simplement `-h` en mode interactif.

----
🎸> --help
----

[[process-creation-songbook]]
=== Processus de création d'un carnet ===

Le **processus classique de création d'un carnet** est le suivant :

- vous créez des chansons ou vous les récupérez depuis notre site,
  - vous écrivez les paroles,
  - vous placez les accords sur les paroles,
- s'ils n'existent pas vous créez les diagrammes d'accord propres à ces chansons,
- vous créez les tablatures, les partitions dont elles ont besoin,
- vous établissez le gabarit de la chanson pour y injecter ces éléments,
- vous créez la table des matières du carnet, donc la liste des chansons,
- vous définissez les caractéristiques du carnet et notamment sa mise en page,
- vous lancez le processus de fabrication du carnet,
- vous ajustez les gabarits des chansons qui peuvent poser problème,
- vous relancez le processus de fabrication du carnet jusqu'à satifaction complète,
- vous construisez la couverture à partir du modèle fourni,
- vous envoyez tout le matériel à votre imprimeur,
- vous chantez et partagez ces chansons avec les autres !

---

[[diag-builder, constructeur de diagramme]]
==== Constructeur de diagramme ====

Outils permettant de construire des diagrammes d'accords pour la guitare.
----
console build diag "schéma"
----

Concernant le schéma à fournir, cf. <<>>.

==== Constructeur de tablatures ====

Pour construire le ou les tablatures (fichiers `.tab`) contenus dans le dossier de la chanson.

----
songbook build tab "titre chanson"
----
