[[songbook-layout]]
=== Layout d'un carnet ===

Le __layout__ d'un carnet, c'est-à-dire sa __mise en forme__ d'un point de vue général, se définit dans les <<options>> du carnet.

Avant de poursuivre, il est important de comprendre que le __layout__ de la chanson n'est pas à confondre avec le __gabarit__ : 

- Le **gabarit** (fichier `.gab`) définit OÙ les éléments des paroles vont se placer dans la page et l'un par rapport à l'autre. Il se définit en général pour chaque chanson.
- Le **layout** définit les métadonnées de la mise en page, comme la policie et la taille des caractères, les marges, les options de mise en page, etc.

En général, dans les carnets, le layout (c'est-à-dire le préset d'options utilisées) est déterminé par la propriété `layout` qui définit une mise en page par défaut (par exemple `layout: regular-B`). La liste des <<app-layouts, layouts de l'application>> suffisent normalement amplement à trouver une mise en forme satisfaisante.

Cependant, si vous voulez modifer certains paramètres, vous pouvez le faire par le biais des infos du carnet (ou de la chanson).

Voir les <<songbook-layout-options>>.

[[common-layouts, Mises en page]]
==== Mises en page par défaut ====

===== Regular-B =====

//TODO: exemple

Caractéristiques

[cols="1,1,4", options="header"]
|====
| Propriété         | Valeur  | Description
| `title_band`      | true    | Titre dans le bandeau
| `lyrics_flux`     | `size`  | couplets/refrain côte à côte
| `diags_position`  | `Int`   | Diagrammes côté reliures
| `diags_size`      | `auto`  | Taille automatique
| `intro_align`     | `Left`  | Les parties « intro » sont mises à gauche.
|====

- Couplets côte à côte
- diagrammes d'accords à l'intérieur
- intro à gauche

===== Regular =====

__Comme le "regular-B" mais le titre sans bandeau__

//TODO: exemple

Caractéristiques

- titre simple, sans bandeau
- Couplets côte à côte
- diagrammes d'accords à l'intérieur

===== Column-B =====

// TODO: Exemple

Caractéristiques

- titre dans un bandeau
- strophes l'une ou dessous de l'autre
- diagrammes d'accords des deux côtés

===== Column =====

__Comme le layout « Column-B » mais titre sans bandeau__

// TODO: Exemple

Caractéristiques

- titre sans bandeau
- strophes l'une ou dessous de l'autre
- diagrammes d'accords des deux côtés
