[[songbook-layout]]
=== Layout d'un carnet ===

TIP: Pour ouvrir directement ce fichier, `songbook open layout --sb "titre carnet"`


C'est un fichier qui doit porter l'extension `.layout` ou `.lay` <<app-extension-driven, peu importe son nom>>.

Dans __SongBook__, on peut le faire chanson par chanson mais il vaut mieux, pour la cohérence esthétique, le définir pour un carnet.

À nouveau la même mise en garde : le __layout__ de la chanson n'est pas à confondre avec le __gabarit__ : 

- Le **gabarit** (fichier `.gab`) définit OÙ les éléments des paroles vont se placer dans la page et l'un par rapport à l'autre.
- Le **layout** (fichier `.lay`) définit les métadonnées de la mise en page, comme la policier et la taille des caractères, les marges, les options de mise en page, etc.

En général, dans les carnets, le layout est déterminé par la propriété `layout` qui définit une mise en page par défaut de l'application. La liste des <<app-layouts, layouts de l'application>> suffisent normalement amplement à trouver son compte.

Cependant, si vous voulez modifer certains paramètres, vous pouvez le faire par le biais d'un layout propre au carnet.

Voir les <<songbook-layout-options>>.

[[common-layouts, Mises en page]]
==== Mises en page par défaut ====

===== Regular-B =====

//TODO: exemple

Caractéristiques

[cols="1,1,4", options="header"]
|====
| Propriété         | Valeur  | Description
| `title_band`      | true    | Titre dans le bandeau
| `lyrics_flux`     | `size`  | couplets/refrain côte à côte
| `diags_position`  | `Int`   | Diagrammes proches des reliures
| `diags_size`      | `auto`  | Taille automatique (?possible)
| `music_position`  | `end`   | La musique sera mise à la fin.
| `intro_align`     | `Left`  | Les parties « intro » sont mises à gauche.
|====

- Couplets côte à côte
- diagrammes d'accords à l'intérieur
- intro à gauche

===== Regular =====

__Comme le "regular-B" mais le titre sans bandeau__

//TODO: exemple

Caractéristiques

- titre simple, sans bandeau
- Couplets côte à côte
- diagrammes d'accords à l'intérieur

===== Column-B =====

// TODO: Exemple

Caractéristiques

- titre dans un bandeau
- strophes l'une ou dessous de l'autre
- diagrammes d'accords des deux côtés

===== Column =====

__Comme le layout « Column-B » mais titre sans bandeau__

// TODO: Exemple

Caractéristiques

- titre sans bandeau
- strophes l'une ou dessous de l'autre
- diagrammes d'accords des deux côtés
