[[options, Configuration]]
=== Options de fabrication ===

On peut définir dans le fichier `infos` (`inf`) toutes les options gérant la fabrication des carnets ou des chansons.

NOTE: Noter que s'il y des options réglées pour le carnet en construction et des options réglées pour la chanson la précédence se fait en fonction de la nature de l'option, sauf dans le cas où l'option `todo: à déterminer` est à `true`.

[cols="2,6,3,1,1", options="header"]
|====
| Prop. | Description 
s| Valeurs | Opt. | Pr.

| `sensitivity` 
| Sensibilité aux erreurs, la façon de les gérer.
| `high`, [`mid`], `low` | `-v` | Carnet

| `song_order_mode`
| Mode de classement des chansons
| `strict`, [`lazy`] | --- | Carnet

| `keep_order`
| Peut remplacer le précédent, respect de l'ordre des chansons.
| `true`, [`false`] | --- | Carnet

| `title_with_labels` | Ajouter les labels aux infos de titre ("Paroles", "Musique", etc.)
| [`false`], `true` | --- | Carnet

|`shrink_diags` | Pour autoriser (`true`) ou non (`false`) le rétrécissement des diagrammes. Note : peut se faire chanson par chanson.
| [`true`], `false` | --- | Song

| `shrink_tabla` | Permission de réduire les tablatures.
| [`true`], `false` | --- | Song

| `shrink_score` | Permission de réduire les partitions.
| [`true`], `false` | --- | Song

| `shrink_lyrics` | Permission de réduire les paroles (font-size).
| `true`, [`false`] | --- | Song

|====


[cols="1,1,5", options="header"]
|====
  | Propritété | Valeur | Description
.3+| `sensitivity`   | `high`  | Le programme s'arrête à la première erreur et la signale.
                    | `mid`   | Les erreurs rencontrées sont listées à la fin de l'opération
                    | `low`   | Aucune interruption, les erreurs sont logguées silencieusement.
.2+|`song_order_mode`| `strict`| L'ordre de la tdm du carnet est respecté scrupuleusement.
                    | `lazy`  | L'ordre peut être modifié pour des raisons d'organisation.

|====


[[song-options, options chanson]]
==== Options propres aux chansons ====

__(donc qu'on ne trouve que dans un fichier `.infos` d'une chanson)__

[cols="2,6,3,1,1", options="header"]
|====
| Prop. | Description | Valeurs | Opt. | Pr.
| `diags` | Options pour les diagrammes d'accords. | <<option-diags, voir>> | --- | Song
|====

[[option-diags]]
===== Options pour les diags =====

----
diags:
  # Pour limiter les diags à une liste d'accords, par exemple seulement
  # les accords compliqués ou propres à la chanson
  list: [Am7, C, Dd7M]
  # Position dans les pages de chanson
  # [Int] : à l'intérieur, donc côté reliure du carnet.
  # Ext   : à l'extérieur, donc à l'opposé de la reliure.
  # Left  : dans une colonne toujours à gauche des paroles.
  # Right : dans une colonne toujours à droite des paroles.
  # Top   : en haut de la page.
  # Bot   : en bas de la page
  # Front : tous les diagrammes avant les paroles en 1^re^ page.
  # End   : tous les diagrammes après les paroles en dernière page.
  position: Left
  
  # Alignement des diags dans leur container (colonne ou rangée)
  # Valeurs possibles en fonction du contenant :
  # Ext/Int/Left/Right : [Center], Top, Bot, Justify
  # Top/Bot/Front/End  : [Center], Left, Right, Justify
  align: Center
  
  # Échelle (zoom) des diagrammes par rapport à la valeur normale
  # C'est une proportion par rapport à 1 (valeur normale).
  # Cette valeur ne s'applique pas si `size` est défini.
  scale: 1.5
  
  # On peut aussi fixer explicitement la taille des diagrammes.
  # Noter que si shrink_diags est true, cette taille pourra être
  # modifiée pour des raisons esthétiques.
  # La valeur a la forme largeur x hauteur. Si une valeur n'est pas
  # définie, elle sera calculée automatiquement par rapport à l'autre
  # "120 x" signifie : "largeur de 120 points et hauteur automatique"
  size: 120 x 
  
----


[[universal-properties, Propriétés universelles]]
=== Propriétés universelles ===

On appelle __propriétés universelles__ les propriétés qui peuvent être attribuées à un grand nombre de paramètres de configuration.

[cols="1,2,4", header]
|====
| Propriété
| Description 
| Valeurs

| `font`
| La fonte générale, par défaut. Une  police et une taille.
| Par défaut : Helvetica 11pt

| `position` 
| Position de l'élément dans la page
| Top = en haut, Left = à gauche, Bot = en bas, Right = à droite, Int = à l'intérieur (des double-pages), Ext = à l'extérieur (des double pages)

|====



=== Placement des diags ===

Dans le <<infos-file>>, c'est le paramètre principal `diags` qui peut contenir les propriétés suivantes :

----
diags:
  list: [liste des accords à traiter]
  position: Top
  scale: 100
----

=== Tablatures et partitions ===

----
tablas:
  position: Under
  
----
