[[songbook-tdm, table des matières]]
=== Table des matières du carnet ===

Pour ouvrir la table des matières d'un carnet :

----
songbook tdm "titre approximatif"
songbook open tdm "titre"
songbook open toc
songbook edit tdm
----

Après avoir défini les données des chansons (<<lyrics-file>>, <<infos-file>>), vous êtes en mesure de définir la table des matières pour définir la liste des chansons utilisée et leur ordre.

Comme défini dans les <<best-practices>>, il vaut mieux que les chansons soient définies dans un autre dossier, séparé. Dans la table des matières, vous pouvez y faire référence par leur identifiant (`id`), leur titre (`title`) ou encore le nom de leur dossier dans le dossier des chansons.

La table des matières est un fichier qui porte l'extension `.tdm`, peu importe son nom.

Imaginons un carnet des tubes des années 1986 qui portera le nom `Carnets/Carnet-tubes-1986/`, on trouvera le fichier : `Carnets/Carnet-tubes-1986/c.tdm` qui pourra débuter par : 

----
- adelaide-arnold-turboust-1986
- Capitaine abandonné
- Démons de minuit (Les)
...
----

* Le premier fait référence à l'identifiant,(`id`) de la chanson dans son fichier `.infos`.
* le second fait référence au titre (`title`) dans le même fichier `.infos`,
* le troisième fait référence au nom du dossier dans le dossier `Chansons`.
 
 [[songbook-tdm-assistant]]
 ==== Construction assistée d'une table des matières ====
 
 ----
 songbook build tdm[ --songbook "Mon nouveau carnet de chant"]
 songbook edit tdm [ --songbook "Mon nouveau carnet de chant"]
 ----
 
 Cette commande affiche la liste des chansons et permet de les choisir pour former une table des matières.
 
 Penser à filtrer la liste des chansons pour les retrouver plus vite, surtout si votre liste est longue.
 
 [[songbook-repeat-song]]
 ==== Répétition de la même chanson ====
 
 On peut tout à fait mettre plusieurs fois la même chanson dans le carnet de chant, par exemple pour l'avoir dans différentes tonalité. Dans ce cas, on ajoute un index entre crochet dans l'idendifiant de la chanson. Si l'identifiant est : 
 
 ----
 - blackbird-the-beatles-1968
 ----
 
 … on pourra utiliser :
 
 ----
 # Par exemple dans mc.tdm
 
 - blackbird-the-beatles-1968 [1]
 - blackbird-the-beatles-1968 [2]
 - blackbird-the-beatles-1968 [3]
 ----
 
On pourra alors préciser les informations précises de la chanson en utilisant ce nouvel identifiant :

----
Mon-Carnet/
  |— mc.tdm
  |— blackbird-the-beatles-1968 [1].infos
  |— blackbird-the-beatles-1968 [2].infos
----

Et les fichiers des informations pourront contenir :

----
# Dans blackbird-the-beatles-1968 [1].infos
font-size: 14pt
font-family: Garamond
----