[[chords-diags, diagrammes d'accords]]
=== Diagrammes d'accords ===

On appelle __diagrammes d'acccord__ ou tout simplement __diag__ ou __diagrammes les petits schémas représentant les accords à la guitare (__il existe des diagrammes pour d'autres instruments à cordes, mais ils ne sont pas utilisés ici__).

Todo: montrer diagramme d'accord.

[[chords-diags-list, liste des diagrammes existants]]
==== Liste des diagrammes ====

On peut obtenir la liste de tous les diagrammes, afin de pouvoir choisir ceux qui nous intéressent pour une chanson, en jouant la commande : 

----
songbook diags
----

Elle ouvre un fichier HTML où sont présentés tous les diagrammes, et il suffit de cliquer sur leur diagrammes pour mettre le nom dans le presse-papier et le coller dans la chanson.

==== Produire ses propres diagrammes ====

On peut aller plus loin et produire ses propres diagrammes personnalisés. Pour ça

----
songbook build diag "<schéma>"
----

Le schéma est très précis et peut s'obtenir avec la commande `diag`.

On peut même directement, si le schéma ne nous intéresse pas, utiliser la commande `diag -o` pour définir le diagramme et produire son image SVG à insérer dans le carnet.

[[song-chords-schemas]]
==== Diagrammes propres à la chanson ====

Une chanson peut définir ses propres schémas dans un fichier `.schemas` (`sche`). Cela est nécessaire lorsque la chanson utilise des accords qui ne sont consignés <<diags-list, nulle part ailleurs>>.

Dans ce fichier, on indique : 

----
<NOM-DANS-LES-PAROLES> : <SCHÉMA DU DIAGRAMME>
# etc. les uns sous les autres
----

Le schéma est obtenu grâce à la commande `diag` qui permet de définir ces diagrammes avec confort et sécurité (l'erreur est pratiquement impossible).

Choisissez bien le nom pour qu'il « n'écrase » pas un accord existant déjà (__rassurez-vous cependant, il ne sera pas vraiment « écrasé »__). C'est ce nom que vous devrez utiliser pour le fichier `.lyr`.