[[chords, accords]]
=== Les accords ===

Les accords, dans les chansons, sont placés avant la syllabe sur laquelle ils doivent être joués. Par exemple, dans l'exemple ci-dessous :

----
Les /am:portes /c:du pé/d:niten/f:cier
----

… l'accord `Am` (La mineur) est joué sur le « por » de « portes », le `C` (Do majeur) est joué sur « du », le `D` (Ré majeur) est joué sur « ni » et le `F` sur « cier ».

NOTE: Cette notation peut paraitre plus complexe à lire que la notation dans ChordPro, mais à la différence de ChordPro, __**SongBook**__ est __pensé pour l'utilisateur__. Et pour l'utilisateur, taper des crochets est compliqué alors que taper « /: » est un jeu d'enfant.

TIP: Noter également que l'<<song-chords-assistant, assistant d'édition des accords>> rend la pose de ces accords particulièrement confortable et rapide ! Une fois qu'on y a gouté, on ne peut plus s'en passer.

Une fois mise en forme, cet extrait devient :

Todo: image résultante

[[chords-syntax]]
==== Syntaxe des accords ====

* **Noms des accords** :
** le nom des accords se mettent en notation batave (La = `a`, Si = `B), Do = `c`, Ré = `D`, Mi = `E`, Fa = `f`, Sol = `G`)
** les notes se marquent en majuscule (`F`) ou en minuscule (`f`), peu importe
** la première lettre d'un « groupe » de lettres est toujours considérée comme la note du nom de l'accord (par exemple le « A » de « abm9 »),
** le signe dièse se marque `d` et le signe bémol par `b` (`Dd` ou `dd` pour Ré dièse majeur, `bb` pour Si bémol majeur),
* **les basses** :
** elles s'indiquent toujours entre crochets (`[fd]`)
** elles seront en italien dans le carnet, mais elles se définissent aussi en notation batave
** elles peuvent se marquer juste après la note de l'accord (`A[c]m7`) ou à la fin de l'accord (`Am7[c]`)
** on peut utiliser les <<only-bass, basses seules>>, sans accords
- on peut __affiner__ l'accord en mettant des indications après un « - », par exemple la case où l'accord doit être joué sur une guitare (`Am-5`)
* **Accords et diagrammes** :
** les accords doivent toujours correspondre à un diagramme (voir la todo: liste des diagrammes),
- lorsque le diagramme n'existe pas, on peut le produire à l'aide du <<diag-schema-producer, constructeur de diagramme>>.
- plusieurs accords peuvent s'enchainer sans espaces entre eux : `/c:/dm:/em:`,
- on peut séparer les accords par n'importe quel signe, souvent une balance pour indiquer qu'ils sont enchainés, joués dans la même mesure : `/c://f:` (noter le `//`, dont le deuxième définit le début de l'accord `/f:`),
- pour marquer que l'accord est joué hors syllabe, au début du vers, on ajoute un trait plat : `/C:_`
- à la fin d'un vers, le trait plat <<trait-plat-usages, n'est pas obligatoire>>

[[only-bass]]
**Basses seules**
----
Don't give /am:up [g][fd]

In /em:this proud land
----

----
/c:_ C'est un en/[b]:droit qui res/am:semble
----

[[trait-plat-usages]]
**Usage du trait plat**

----
/c:_ Au début mais /dm:pas à la fin /g: /g7:
----