[[chords, accords]]
=== Les accords ===

Les accords, dans les chansons, sont placés avant la syllabe sur laquelle ils doivent être joués. Par exemple, dans l'exemple ci-dessous :

----
Les /am:portes /c:du pé/d:niten/f:cier
----

… l'accord `Am` (La mineur) est joué sur le « por » de « portes », le `C` (Do majeur) est joué sur « du », le `D` (Ré majeur) est joué sur « ni » et le `F` sur « cier ».

Une fois mise en forme, cela donne :

Todo: image résultante

- le nom des notes se mettent en notation batave (La = `a`, Si = `B), Do = `c`, Ré = `D`, Mi = `E`, Fa = `f`, Sol = `G`)
- les notes se marquent en majuscule (`F`) ou en minuscule (`f`)
- la première lettre d'un groupe de lettres est toujours considérée comme une note,
- le signe dièse se marque `d` et le signe bémol par `b` (`Dd` ou `dd` pour Ré dièse majeur, `bb` pour Si bémol majeur),
- les basses se marquent entre crochets (`[fd]`)
- les basses peuvent se marquer juste après la note de l'accord (`A[c]m7`) ou à la fin de l'accord (`Am7[c]`)
- on peut utiliser les <<only-bass, basses seules>>, sans accords
- on peut __affiner__ l'accord en mettant des indications après un « - », par exemple la case où l'accord doit être joué sur une guitare (`Am-5`)
- les accords doivent toujours correspondre à un diagramme (voir la todo: liste des diagrammes),
- lorsque le diagramme n'existe pas, on peut le produire à l'aide du <<diag-builder, constructeur de diagramme>>.
- plusieurs accords peuvent s'enchainer sans espaces entre eux : `/c:/dm:/em:`,
- on peut séparer les accords par n'importe quel signe, souvent une balance pour indiquer qu'ils sont enchainés, joués dans la même mesure : `/c://f:` (noter le `//`, dont le deuxième définit le début de l'accord `/f:`),
- pour marquer que l'accord est joué hors syllabe, au début du vers, on ajoute un trait plat : `/C:_`
- à la fin d'un vers, le trait plat <<trait-plat-usages, n'est pas obligatoire>>

[[only-bass]]
**Basses seules**
----
Don't give /am:up [g][fd]

In /em:this proud land
----

----
/c:_ C'est un en/[b]:droit qui res/am:semble
----

[[trait-plat-usages]]
**Usage du trait plat**

----
/c:_ Au début mais /dm:pas à la fin /g: /g7:
----