[[diags, diagrammes d'accords]]
=== Diagrammes d'accords ===

On appelle __diagrammes d'acccord__ ou tout simplement __diag__ ou __diagrammes les petits schémas représentant les accords à la guitare (__il existe des diagrammes pour d'autres instruments à cordes, mais ils ne sont pas utilisés ici__).

Todo: montrer diagramme d'accord.

[[diags-list, liste des diagrammes existants]]
==== Liste des diagrammes ====

On peut obtenir la liste de tous les diagrammes, afin de pouvoir choisir ceux qui nous intéressent pour une chanson, en jouant la commande : 

----
songbook diags
----

Elle ouvre un fichier HTML où sont présentés tous les diagrammes, et il suffit de cliquer sur leur diagrammes pour mettre le nom dans le presse-papier et le coller dans la chanson.

Bien que vous n'ayez normalement jamais à utiliser cette commande, nous l'indiquons dans le cas où vous touchiez les fichiers SVG par inadvertance. Elle actualise tous les fichiers SVG des accords.

----
songbook update diags
----


==== Produire ses propres diagrammes ====

On peut aller plus loin et produire ses propres diagrammes personnalisés. Pour ça

----
songbook build diag "<schéma>"
----

Le schéma est très précis et peut s'obtenir avec la commande `diag`.

On peut même directement, si le schéma ne nous intéresse pas, utiliser la commande `diag -o` pour définir le diagramme et produire son image SVG à insérer dans le carnet.


[[song-schemas, diagrammes de la chanson]]
==== Diagrammes propres à la chanson ====

Une chanson peut définir ses propres schémas dans un fichier `.schemas` (`sche`). Cela est nécessaire lorsque la chanson utilise des accords qui ne sont consignés <<diags-list, nulle part ailleurs>>.

**OU**, plus important, lorsqu'elle utilise des positions particulières d'accord pouvant déjà exister. Dans ce cas, les accords qu'elle définit sont **prioritaires** sur les accords existants.

Dans le fichier des schémas, on indique : 

----
<NOM-DANS-LES-PAROLES> : <SCHÉMA DU DIAGRAMME>
# etc. les uns sous les autres
----

Le schéma est obtenu grâce à la commande `diag` qui permet de définir ces diagrammes avec confort et sécurité (l'erreur est pratiquement impossible).

Pour être clair, voilà la démarche à utiliser :

__Les commandes sont données en mode interactif (`songbook -i`) avec la chanson mise en chanson courante (`🎸> use song "ma chanson"`)__

[cols="4,1"]
|====
| S'assurer d'abord que l'accord n'existe pas déjà  | `diags`
| Ouvrir ou créer le fichier `.schemas`             | `open schemas`
| Dans un autre Terminal, lancer l'éditeur de diag  | `diag` (hors interactif)
| Définir le diagramme                              |
| Ne pas l'enregistrer pour l'application           |
| Coller le schéma dans le fichier `.schemas`       | combo:Cmd+v[]
| Lancer la production des fichiers SVG             | `build diags`
|====

[[diags-position]]
==== Position et taille des diagrammes ====

Pour placer les diagrammes dans la chanson ou le carnet, utiliser le <<gabarit-file>> de la chanson ou les règles du <<songbook-layout layout (mise en page)>> du carnet.

Pour redimensionner les diags, vous pouvez jouer sur plusieurs <<diags-options, options spécialisées>>.

==== Limiter la liste des diagrammes ====

Vous pouvez, dans les carnets dont l'option `diag_list` est réglée à `list`, définir avec l'option `diag_list` aussi la liste des seuls diags à afficher. Cf. <<diags-options, les options en matière de diagrammes>>. 

[[diags-missing]]
==== Diagrammes manquant ====

On peut obtenir la liste des diags introuvables (ni dans l'app ni dans la chanson).

----
songbook missing diags --song "titre approx"
# => Liste dans la chanson

songbook missing diags --songbook "titre approx"
# => Liste dans le carnet de chant

songbook missing diags --all
# => Liste dans toutes les chansons
----

En <<interactive-mode, mode interactif>>, c'est la chanson ou le carnet courant qui est pris en référence :

----
songbook -i
🎸> use song titre-approx
🎸> missing diags
# => Liste des diagrammes manquant dans la chanson.
----