[[gabarit-file, gabarit de la chanson]]
=== Gabarit de la chanson ===

TIP: Pour ouvrir directement ce fichier, `songbook open gabarit --song "titre chanson"`

Alors que <<song-layout, le fichier `.layout`>> définit les __règles__ régissant la mise en forme de la chanson, laissant la liberté à __**SongBook**__ de prendre toutes les décisions pour produire un affichage cohérent et esthétique, le fichier `.gabarit` va définir très précisément le positionnement des éléments de la chanson.

Peu importe son nom pourvu que son extension soit `.gab` (comme "GABarit", `fichier.gab`) ou `.gabarit` (`machanson.gabarit`).

On trouve principalement ce fichier dans le <<song-folder>>, sa place naturelle, entendu que chaque chanson, pratiquement, a besoin d'un mise en place particulière en fonction de sa structure, de ses paroles, etc. Dans ce cas, il définira l'affichage de la chanson quel que soit le carnet où elle est utilisée.

Exceptionnellement, on peut trouver le gabarit d'une chanson dans le <<songbook-folder>> pour définir exceptionnellement le gabarit de telle chanson dans ce carnet-là, s'il a une forme particulière. Dans ce cas, le nom du fichier doit être impérativement `<id chanson> [<...>].gab<arit>`. Par exemple : `id-de-ma-chanson [2 réduit].gabarit`.

==== Définir le gabarit ====

La fonction principale de ce fichier est de définir la position et l'aspect des différents éléments de la chanson, que ce soit les paroles, les partitions ou les images.

Pour définir la position des paroles, le fichier gabarit reprend les éléments définis entre crochets dans le <<lyrics-file, fichier des paroles>>.

Par exemple, si on trouve ça dans le fichier `.lyr` : 

----
{couplet-1}
Le premier couplet
...

{couplet-2}
Le deuxième couplet
...

{couplet-3}
Le troisième couplet
...
----

… alors on peut définir dans le gabarit des choses comme : 

----
{lyrics: couplet-1} // {lyrics: couplet-2}
{break; tab: mon-fichier-tablature; align:center; width:400pt; }
{couplet-3; block-align:center; align:center; }
...
----

===== Définitions pour les diags =====

On peut définir les propriétés des diagrammes d'accord au début du fichier gabarit.

----
{diags; position:End; width:50px;}
----

[[gabarit-insert-tablas]]
===== Insertion de tablatures =====

Pour insérer une tablature à l'endroit voulu, on lui trouve un identifiant unique, on définit la tablature à prendre à l'aide de la propriété `tab` suivi du nom composé ou non de la tablature :

----
{intro; tab:intro;}
----

On peut faire suivre bien sûr par toutes les propriétés qui peuvent s'appliquer aux images.

----
{intro; tab:intro; height:50px;}
----

Une des fonctionnalités formidable des tablatures est la faculté d'associer plusieurs tablatures juste avec le signe `+`, ce qui apporte beaucoup de granularité. Par exemple, si vous avez une tablature `riff-intro.tab`, une autre `couplet-normal.tab` et une troisième `fin.tab` vous pouvez les assembler de cette manière : 

----
{intro; tab:riff-intro+couplet-normal+fin;}
----

Cela créera une **unique** tablature avec les trois éléments !

Bien sûr, les tablatures fonctionnent exactement comme les autres éléments et vous pouvez donc utiliser des marques comme ci-dessous pour placer relativement les éléments :

----
{intro; tab:intro;} // {couplet-1}
----

Ci-dessus, la tablature `intro.tab` sera placée en vis à vis du premier couplet.

[[gabarit-insert-score]]
===== Insertion de partitions =====

Les partitions répondent aux mêmes fonctionnalités que <<gabarit-insert-tablas, la tablatures dans le gabarit>> donc vous pouvez consulter cette partie (ci-dessus) pour voir comment utiliser les partitions dans le fichier `.gabarit` de la chanson.

[[gabarit-insert-image]]
===== Insertion d'image =====

Todo: à définir. Normalement, ça devrait être `{deco; img: image.jpg; title: L'illustration;}`