[[gabarit-file, gabarit de la chanson]]
=== Gabarit de la chanson ===

TIP: Pour ouvrir directement ce fichier, `songbook open gabarit --song "titre chanson"`

**TODO Ce fichier est à reprendre entièrement pour voir ce qui doit être implémenté.

Alors que <<song-layout, le fichier `.layout`>> définit les __règles__ régissant la mise en forme de la chanson, laissant la liberté à __**SongBook**__ de prendre toutes les décisions pour produire un affichage cohérent et esthétique, le fichier `.gabarit` va définir très précisément le positionnement des éléments de la chanson.

On peut trouver ce fichier : 

- dans le <<song-folder>>, avec n'importe quel nom à extension `.gabarit` ou `.gab`. Dans ce cas, il définira l'affichage de la chanson quel que soit le carnet où elle est utilisée.
- dans le <<songbook-folder>>, pouvant définir le gabarit de toutes les chansons du carnet (extrêmement rare et dangereux) ou le bagarit de certaines chansons. Dans ce cas, le nom doit être impérativement `<id chanson>.gab`.

==== Définir le gabarit ====

Le fichier gabarit reprend les éléments définis entre crochets dans le <<lyrics-file, fichier des paroles>>.

Par exemple, si on trouve ça dans le fichier `.lyr` : 

----
{couplet-1}
Le premier couplet
...

{couplet-2}
Le deuxième couplet
...

{couplet-3}
Le troisième couplet
...
----

… alors on peut définir dans le gabarit des choses comme : 

----
{couplet-1; margin-left: 1cm;}
{couplet-2; margin-right: 1cm; font-size:0.85em;}
{tabla: mon-fichier-tablature; align:center; width:400pt; }
{couplet-3; block-align:center; align:center; }
...
----

===== Définitions pour les diags =====

On peut définir les propriétés des diagrammes d'accord au début du fichier gabarit.

----
{diags; position:End; width:50px;}
----

[[gabarit-insert-tablas]]
===== Insertion de tablatures =====

Pour insérer une tablature à l'endroit voulu, on lui trouve un identifiant unique, on définit la tablature à prendre à l'aide de la propriété `tab` suivi du nom composé ou non de la tablature :

----
{intro; tab:intro;}
----

On peut faire suivre bien sûr par toutes les propriétés qui peuvent s'appliquer aux images.

----
{intro; tab:intro; height:50px;}
----

Une des fonctionnalités formidable des tablatures est la faculté d'associer plusieurs tablatures juste avec le signe `+`, ce qui apporte beaucoup de granularité. Par exemple, si vous avez une tablature `riff-intro.tab`, une autre `couplet-normal.tab` et une troisième `fin.tab` vous pouvez les assembler de cette manière : 

----
{intro; tab:riff-intro+couplet-normal+fin;}
----

Cela créera une **unique** tablature avec les trois éléments !

Bien sûr, les tablatures fonctionnent exactement comme les autres éléments et vous pouvez donc utiliser des marques comme ci-dessous pour placer relativement les éléments :

----
{intro; tab:intro;} // {couplet-1}
----

Ci-dessus, la tablature `intro.tab` sera placée en vis à vis du premier couplet.

[[gabarit-insert-score]]
===== Insertion de partitions =====

Les partitions répondent aux mêmes fonctionnalités que <<gabarit-insert-tablas, la tablatures dans le gabarit>> donc vous pouvez consulter cette partie (ci-dessus) pour voir comment utiliser les partitions dans le fichier `.gabarit` de la chanson.

[[gabarit-insert-image]]
===== Insertion d'image =====


[[gabarit, le fichier Gabarit]]
=== Fichier gabarit ===

__Fichier définissant les gabarits, c'est-à-dire la disposition des éléments dans la page.__

Peu importe son nom pourvu que son extension soit `.gab` (comme "GABarit"). `fichier.gab`

Sa fonction principale est de définir la position et l'aspect des différents éléments de la chanson.

Par exemple : 

----
\# Dans le fichier machanson.gab

{title: band; infos: beside;}

{lyrics: couplet-1} // {lyrics: couplet-2}

{tabla: accompagnement;}

{refrain-1; align: center; text_align: left;}

----




----
À placer

{
  title: band|simple;   # type de titre. note : pris dans .infos
  infos: under|beside;  # place des infos
  align: left;          # Alignement
}

{
  diags: all| [liste des accords à traiter];
  position: Top|Left|Bot|Rigth|Ext|Int; 
}

{ 
  tabla: fichier-sans-ext;
  shrink: true; # on peut réduire pour tenir
}

{
  score: fichier-sans-ext;
  shrink: true; # on peut réduire pour tenir
}

{
  song: couplet-1; # partie à placer (prise dans .lyr)
}

\# Parties côte à côte (deux couplets par exemple)
{song: ...} // {song: ...}
----


==== Gabarit dans un carnet de chant ====

Comme nous l'avons vu, lorsque le fichier est dans un carnet de chant, et qu'il porte l'identifiant d'une chanson, il définit le gabarit à utiliser pour la chanson spécifiquement pour ce carnet-là et aucun autre (sauf duplication du fichier dans un autre carnet, évidemment). Cela permet d'adapter la chanson à une disposition de carnet particulière.