[[infos-file]]
=== Fichier des informations de la chanson ===

TIP: Pour ouvrir directement ce fichier, `songbook open infos --song "titre chanson"`

Les informations de la chanson sont consignés dans son <<song-folder, dossier>> dans une fichier portant l'extension `.infos` (ou `inf` en mode réduit) et un nom racine quelconque (p.e. `mc.inf`).

Ce fichier est un <<pseudo-yaml-format, format pseudo YAML>> (liste superposée de `propriétés: valeurs`)

On met dans ce fichier toutes les informations utiles, à savoir :

----
id: Identifiant simple de la chanson
title: Titre de la chanson (tel qu'il sera affiché)
performer: l'interprète de la chanson
composer: Compositeur ou compositrice de la chanson
lyrics: Auteur ou autrice des paroles
year: L'année de sortie
# Optionnel (utiliser avec prudence)
layout: La disposition utilisée (par défaut, regular)
----

Par exemple : 

----
id: dont-give-up-gabriel-1986
title: Don’t Give Up
performer: Peter Gabriel et Kate Bush
composer: P. Gabriel
lyrics: P. Gabriel
year: 1986

layout: regular
----

Notez que si vous utilisez la commande **`songbook create song`** pour créer une nouvelle chanson, ce fichier sera rempli pour vous (ou prérempli en fonction des informations récoltées sur le web).

Cet fichier contient aussi la définition des <<options>> propres à la chanson (options partagées par le carnet si c'est lui qui est contruit).