[[lyrics-file, les strophes]]
=== Les paroles ===

Conformément à la <<terminology>> de __**SongBook**__, on appelle __STROPHE__ les groupes de vers formant un couplet, un refrain ou autre texte parlé ou chanté au cours de la chanson.

[[strophe-definition, définition de la strophe]]
==== Définition de la strophe ====

La __strophe__ se définit dans les <<lyrics-file, fichier des lyrics>> par une première ligne entre crochets : 

----
{couplet-1}
Un beau jour ou peut-être une nuit
Près d'un lac je m'étais endormie
Quand soudain semblant crever le ciel
Et venant de nulle part 
surgit un aigle noir
----

Cette définition (texte entre crochets) peut employer toutes les <<text-properties, propriété propres aux textes>>.

----
{couplet-1; font-size:14pt; align:center;}
Un beau jour ou peut-être une nuit
Près d'un lac je m'étais endormie
----

Cependant, la chanson pouvant être employée dans différents carnets, il vaut mieux définir ces propriétés dans un fichier gabarit propre au carnet comme cela est expliqué dans <<best-practices>>.

=== Fichier des paroles et accords ===

Peu importe le nom-racine du fichier des paroles, il suffit qu'il porte l'extension `.lyr` ou `.lyrics` pour que l'application le reconnaisse.

Ce fichier contient évidemment les paroles. Mais aussi les accords.

Le format est simple, il suffit de mettre entre crochet comment s'appelle la strophe, sans espaces, par exemple "{couplet-2}", "{refrain}". Ces marques serviront dans le <<gabarit>> des pages.

Pour les accords, contrairement à ChordPro, qui utilise des crochets peut-être clairs visuellement mais pas pratiques à taper au clavier, nous avons opté pour un système simple à taper : "/accord:Syllabe du texte".

Nous expliquons ci-dessous comment formater les accords par rapport aux paroles, mais vous n'en aurez pas besoin si vous utilisez **<<song-chords-assistant, l'assistant de pose des accords>>**.

L'accord doit être placé avant la syllabe sur laquelle il doit être joué, ou avant un « _ » (trait plat) s'il n'est pas joué sur une syllabe.

----
{couplet-1}
Les /am:Portes /c:du pé/d:niten/f:cier
----

Notez que les accords sont précisés en minuscule, par commodité d'écriture, mais qu'ils seront toujours mis en majuscules ensuite dans le carnet de chant.

La marque `{couplet-1}` par exemple sera reprise dans le <<gabarit>> du carnet ou de la chanson pour savoir où et comment placer les strophes en question.