[[lyrics-file, les strophes]]
=== Les paroles ===

Conformément à la <<terminology>> de __**SongBook**__, on appelle __STROPHE__ les groupes de vers formant un couplet, un refrain ou autre texte parlé ou chanté au cours de la chanson.

[[strophe-definition, définition de la strophe]]
==== Définition de la strophe ====

La __strophe__ se définit dans les <<lyrics-file, fichier des lyrics>> par une première ligne entre crochets : 

----
{couplet-1}
Un beau jour ou peut-être une nuit
Près d'un lac je m'étais endormie
Quand soudain semblant crever le ciel
Et venant de nulle part 
surgit un aigle noir
----

Cette définition (texte entre crochets) peut employer toutes les <<text-properties, propriété propres aux textes>>.

----
{couplet-1; font-size:14pt; align:center;}
Un beau jour ou peut-être une nuit
Près d'un lac je m'étais endormie
----

Cependant, la chanson pouvant être employée dans différents carnets, il vaut mieux définir ces propriétés dans un fichier gabarit propre au carnet comme cela est expliqué dans <<best-practices>>.

=== Fichier des paroles et accords ===

Peu importe son nom (root), il doit porter l'extension `.lyr`.
`fichier.lyr`

Il présente évidemment les paroles.

Le format est simple, il suffit de mettre entre crochet comment s'appelle la strophe, sans espaces, par exemple "{couplet-2}", "{refrain}". Ces marques serviront dans le <<gabarit>> des pages.

Le plus délicat, ce sont les accords. Contrairement à ChordPro, qui utilise des crochets peut-être clairs visuellement mais infernaux à taper au clavier, nous avons opté pour un système simple à taper : "/accord:Syllabe du texte".

Donc, comme vous le comprenez, l'accord doit être placé contre la syllabe sur laquelle il doit être joué.

----
{couplet-1}
Les /am:Portes /c:du pé/d:niten/f:cier
----

Notez que les accords sont précisés en minuscule, par commodité d'écriture, mais qu'ils seront toujours mis en majuscules ensuite.

La marque `{couplet-1}` par exemple sera reprise dans le <<gabarit>> du carnet ou de la chanson pour savoir où et comment placer les strophes en question.

[[riffs, riffs]]
==== Riffs, les « petit bout de musique » ====

Il est possible, grâce à la balise `/riff ...:` d'ajouter un petit bout de musique, un __riff__ par exemple, comme dans la chanson __Le Sud__ (riff de début) ou la chanson __All You Need Is Love__ (riff de fin):

----
# Le Sud
/riff intro: _ C'est un en/c:droit qui res/c/b:semble
----

----
# All You Need Is Love
/f:Love, /c:love, /dm7:love /riff riff: _
----

Pour ces deux riffs, on doit trouver les fichiers `riff.tab` (tablature) ou `riff.score` (partition) et `intro.tab` ou `intro.score` quelque part dans le dossier de la chanson.

Pour la définition d'une tablature ou d'une partition, voir <<tablature>> et <<score>>.