[[lyrics-file, les strophes]]
=== Les paroles ===

Conformément à la <<terminology>> de __**SongBook**__, on appelle __STROPHE__ les groupes de vers formant un couplet, un refrain ou autre texte parlé ou chanté au cours de la chanson.

[[strophe-definition, définition de la strophe]]
==== Définition de la strophe ====

La __strophe__ se définit dans les <<lyrics-file, fichier des lyrics>> par une première ligne entre crochets : 

----
{couplet-1}
Un beau jour ou peut-être une nuit
Près d'un lac je m'étais endormie
Quand soudain semblant crever le ciel
Et venant de nulle part 
surgit un aigle noir
----

Cet identifiant (`couplet-1`) peut avoir n'importe quel nom, peu importe. Il servira dans le <<gabarit-file, gabarit d'affichage>> pour préciser où et comment le texte doit être placé, et avec quelles caractéristiques (voir <<text-properties, propriété propres aux textes>>). Par exemple : 

----
# Dans ma-chanson.gabarit
{couplet-1; font-size:14pt; align:center;} // {couplet-2}
----

La seule précaution à prendre est de **ne jamais donner le même identifiant à deux strophes**. Il en résulterait une confusion pour le __parseur__. Mais rassurez-vous, l'erreur vous sera signalée.


=== Fichier des paroles et accords ===

Peu importe le nom-racine du fichier des paroles, il suffit qu'il porte l'extension `.lyr` ou `.lyrics` pour que l'application le reconnaisse.

Ce fichier contient évidemment les paroles. Mais aussi **les accords**. Pour les accords, contrairement à ChordPro, qui utilise des crochets peut-être clairs visuellement mais pas du tout pratiques à taper au clavier, nous avons opté pour un système simple à taper : "/accord:Syllabe du texte".

TIP: Nous expliquons ci-dessous comment formater les accords par rapport aux paroles, mais vous n'en aurez pas besoin si vous utilisez **<<song-chords-assistant, l'assistant de pose des accords>>**, que nous vous recommandons vivement si vous voulez entrer les accords avec un confort et une efficacité maximals.

L'accord doit être placé avant la syllabe sur laquelle il doit être joué, ou avant un « _ » (trait plat) s'il n'est pas joué sur une syllabe.

----
{couplet-1}
Les /am:Portes /c:du pé/d:niten/f:cier
----

Notez que les accords sont précisés en minuscule, par commodité d'écriture, mais qu'ils seront toujours mis en majuscules ensuite dans le carnet de chant.

La marque `{couplet-1}` par exemple sera reprise dans le <<gabarit-file>> du carnet ou de la chanson pour savoir où et comment placer les strophes en question.

Pour souligner une syllabe (ou plusieurs), encadrez-la de crochets, par exemple `cha[peau]` : le rendu affiche "chapeau" avec "peau" souligné, les crochets eux-mêmes ne sont jamais imprimés.